### ISSUE TITLE
Abstract a set of LLM models to enable overrides and custom models

### ISSUE THREAD

**Issue by yoziru** [grafana/grafana-llm-app#309]
Instead of explicitly defining a model in each LLM feature implementation, have an abstraction that points to a configurable model name in grafana-llm-app.

E.g. instead of 
```ts
await llms.openai.chatCompletions({
   model: 'gpt-4-turbo',
   …
})
```

Use
```ts
await llms.openai.chatCompletions({
   model: llms.models.chat.MODEL_HIGH_ACCURACY,
   …
})
```

To keep things simple, we can start with 2 capability based abstractions for the 2 different models currently in use:
- models.chat.MODEL_DEFAULT = “gpt-3.5-turbo”
- models.chat.MODEL_HIGH_ACCURACY = "gpt-4-turbo"

To ease migration, we can map the model for existing implementations using grafana-llm-app to fall back on either of these 2 

These 2 fields would then be exposed through the plugin config, where the user can set / override the defaults.
- we could fetch the available models from `/v1/models` and show them in a dropdown (should also work with any OpenAI compatible inference server such as Ollama, LMStudio or vLLM)

Should resolve both these issues:
- https://github.com/grafana/grafana-llm-app/issues/212
- https://github.com/grafana/grafana-llm-app/issues/162
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-llm-app/pull/315
- [ ] https://github.com/grafana/grafana-llm-app/issues/322
- [ ] https://github.com/grafana/grafana-llm-app/issues/323
- [ ] https://github.com/grafana/grafana-llm-app/issues/324
```

**Comment by csmarchbanks** [comment]
https://github.com/grafana/grafana-llm-app/pull/315 starts the work on this for the backend.

**Comment by yoziru** [comment]
Done as of https://github.com/grafana/grafana-llm-app/releases/tag/0.10.0
